# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='e', upload_to='uploaded_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='posted',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 16, 17, 6, 13, 920444, tzinfo=utc), verbose_name='date posted'),
            preserve_default=False,
        ),
    ]
